/* Generated By:JavaCC: Do not edit this line. SqlParserConstants.java */
package testsql;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SqlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SELECT = 6;
  /** RegularExpression Id. */
  int COMMA = 7;
  /** RegularExpression Id. */
  int LPAREN = 8;
  /** RegularExpression Id. */
  int RPAREN = 9;
  /** RegularExpression Id. */
  int FROM = 10;
  /** RegularExpression Id. */
  int WHERE = 11;
  /** RegularExpression Id. */
  int AS = 12;
  /** RegularExpression Id. */
  int INNER = 13;
  /** RegularExpression Id. */
  int LEFT = 14;
  /** RegularExpression Id. */
  int RIGHT = 15;
  /** RegularExpression Id. */
  int JOIN = 16;
  /** RegularExpression Id. */
  int ON = 17;
  /** RegularExpression Id. */
  int AND = 18;
  /** RegularExpression Id. */
  int OR = 19;
  /** RegularExpression Id. */
  int DOT = 20;
  /** RegularExpression Id. */
  int SQ = 21;
  /** RegularExpression Id. */
  int IN = 22;
  /** RegularExpression Id. */
  int GROUP = 23;
  /** RegularExpression Id. */
  int BY = 24;
  /** RegularExpression Id. */
  int ORDER = 25;
  /** RegularExpression Id. */
  int ASC = 26;
  /** RegularExpression Id. */
  int DESC = 27;
  /** RegularExpression Id. */
  int LIMIT = 28;
  /** RegularExpression Id. */
  int PLUS = 29;
  /** RegularExpression Id. */
  int NUMBER = 30;
  /** RegularExpression Id. */
  int EQ = 31;
  /** RegularExpression Id. */
  int GE = 32;
  /** RegularExpression Id. */
  int LE = 33;
  /** RegularExpression Id. */
  int GT = 34;
  /** RegularExpression Id. */
  int LT = 35;
  /** RegularExpression Id. */
  int IDENTIFIER = 36;
  /** RegularExpression Id. */
  int SINGLE_QUOTE_STRING = 37;
  /** RegularExpression Id. */
  int END = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"select\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"from\"",
    "\"where\"",
    "\"as\"",
    "\"inner\"",
    "\"left\"",
    "\"right\"",
    "\"join\"",
    "\"on\"",
    "\"and\"",
    "\"or\"",
    "\".\"",
    "\"\\\'\"",
    "\"in\"",
    "\"group\"",
    "\"by\"",
    "\"order\"",
    "\"asc\"",
    "\"desc\"",
    "\"limit\"",
    "\"+\"",
    "<NUMBER>",
    "\"=\"",
    "\">=\"",
    "\"<=\"",
    "\">\"",
    "\"<\"",
    "<IDENTIFIER>",
    "<SINGLE_QUOTE_STRING>",
    "\"#\"",
  };

}
